#!/usr/bin/env python3
"""
baseline_inventory.py — Phase 0 baselining (CCS-1, CCS-2, CCS-4).

Probes every local cluster, reports what is actually configured today, and can
emit a ready-to-edit `es_clusters.json` with the observed values pre-filled as
the baseline.

This is the honest way to do Phase 0: read reality first, then decide what
"expected" should be. Nothing here judges health — that is the collector's job.
It only records what is there.

The clusters file it reads needs `name` and `base_url` per cluster; the
`expected_remotes` block may be empty, which is exactly the state you are in
before baselining.

Usage:
    # See what is really configured, as a Markdown table for the review doc:
    python3 tools/baseline_inventory.py --clusters es_clusters.json --format markdown

    # Same, as JSON:
    python3 tools/baseline_inventory.py --clusters es_clusters.json --format json

    # Generate a baseline file from what is live, then review every line of it:
    python3 tools/baseline_inventory.py --clusters es_clusters.json \
        --emit-baseline es_clusters.generated.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any, Dict, List

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ccs_monitor.config import ConfigError, load_config  # noqa: E402
from ccs_monitor.credentials import CredentialError, build_provider  # noqa: E402
from ccs_monitor.evaluate import configured_max, connected_count  # noqa: E402
from ccs_monitor.logging_setup import configure_logging  # noqa: E402
from ccs_monitor.probe import probe_cluster  # noqa: E402

EXIT_OK = 0
EXIT_FAILED = 1
EXIT_CONFIG_ERROR = 2


def collect(config, provider) -> List[Dict[str, Any]]:
    """Probe every enabled cluster and flatten what each remote reports."""
    rows: List[Dict[str, Any]] = []
    for cluster in config.enabled_clusters:
        probe = probe_cluster(cluster, provider)
        if not probe.ok:
            rows.append({
                "cluster": cluster.name,
                "environment": cluster.environment,
                "remote": None,
                "error": probe.error,
                "error_kind": probe.error_kind,
            })
            continue

        if not probe.remotes:
            rows.append({
                "cluster": cluster.name,
                "environment": cluster.environment,
                "remote": None,
                "error": "no remotes configured on this cluster",
                "error_kind": "empty",
            })
            continue

        for name, observed in sorted(probe.remotes.items()):
            rows.append({
                "cluster": cluster.name,
                "environment": cluster.environment,
                "remote": name,
                "connected": observed.get("connected"),
                "nodes_connected": connected_count(observed),
                "max_connections": configured_max(observed),
                "mode": observed.get("mode"),
                "initial_connect_timeout": observed.get("initial_connect_timeout"),
                "skip_unavailable": observed.get("skip_unavailable"),
                "seeds": observed.get("seeds"),
                "proxy_address": observed.get("proxy_address"),
                "in_baseline": name in cluster.expected_remotes,
            })
    return rows


def print_markdown(rows: List[Dict[str, Any]]) -> None:
    """The inventory table CCS-1 asks for, ready to paste into the review doc."""
    print("# Phase 0 — CCS remote inventory (observed)\n")
    print("Generated by `tools/baseline_inventory.py`. These are **observed** values, not")
    print("agreed baselines. Review each row, then record the agreed expectation in")
    print("`es_clusters.json` (CCS-2) and note the skip_unavailable risk (CCS-4).\n")
    print("| Local cluster | Env | Remote | Connected | Nodes/sockets | Max | Mode | Connect timeout | skip_unavailable | In baseline |")
    print("|---|---|---|---|---|---|---|---|---|---|")

    for row in rows:
        if row.get("error"):
            print(
                f"| {row['cluster']} | {row['environment']} | — | **{row['error_kind']}** | — | — | "
                f"— | — | — | — |"
            )
            continue
        skip = row.get("skip_unavailable")
        skip_cell = "**true** ⚠" if skip is True else str(skip).lower()
        print(
            f"| {row['cluster']} | {row['environment']} | `{row['remote']}` | "
            f"{str(row.get('connected')).lower()} | {row.get('nodes_connected')} | "
            f"{row.get('max_connections')} | {row.get('mode')} | "
            f"{row.get('initial_connect_timeout')} | {skip_cell} | "
            f"{'yes' if row.get('in_baseline') else '**no**'} |"
        )

    skippable = [r for r in rows if r.get("skip_unavailable") is True]
    if skippable:
        print("\n## skip_unavailable risk (CCS-4)\n")
        print("Degradation on these remotes can be dropped from cross-cluster results without")
        print("any downstream error — a healthy-looking dashboard can be silently incomplete:\n")
        for row in skippable:
            print(f"- `{row['cluster']}` / `{row['remote']}`")
        print("\nConsider `escalate_warning_when_skip_unavailable: true` in the severity policy")
        print("for the environments that host them.")

    errors = [r for r in rows if r.get("error")]
    if errors:
        print("\n## Clusters that could not be inventoried\n")
        for row in errors:
            print(f"- `{row['cluster']}`: {row['error']}")


def build_baseline(config, rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Turn observed state into a baseline file, pre-filled with today's values."""
    with open(config.source_path, "r", encoding="utf-8") as handle:
        document = json.load(handle)

    by_cluster: Dict[str, Dict[str, Any]] = {}
    for row in rows:
        if row.get("error") or not row.get("remote"):
            continue
        entry: Dict[str, Any] = {
            "expected_nodes": row.get("nodes_connected"),
            "expected_mode": row.get("mode"),
            "expected_skip_unavailable": row.get("skip_unavailable"),
            "expected_initial_connect_timeout": row.get("initial_connect_timeout"),
        }
        entry = {k: v for k, v in entry.items() if v is not None}
        by_cluster.setdefault(row["cluster"], {})[row["remote"]] = entry

    document["_generated_note"] = (
        "Generated by tools/baseline_inventory.py from OBSERVED state. Every expected_* "
        "value is what the cluster reported at generation time, NOT an agreed baseline. "
        "Review each one (CCS-2) before use: if a remote was already degraded when this "
        "ran, its degraded state has just been recorded as 'expected'."
    )
    for cluster in document.get("clusters", []):
        observed = by_cluster.get(cluster.get("name"))
        if observed:
            cluster["expected_remotes"] = observed
    return document


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description="Phase-0 baseline inventory of CCS remotes.")
    parser.add_argument("-c", "--clusters", default="es_clusters.json",
                        help="Cluster inventory file (default: %(default)s).")
    parser.add_argument("-f", "--format", choices=("markdown", "json", "table"), default="markdown")
    parser.add_argument("--emit-baseline", metavar="PATH",
                        help="Write an es_clusters.json pre-filled with the observed values.")
    parser.add_argument("--cluster", action="append", dest="only_clusters", metavar="NAME",
                        help="Inventory only this cluster (repeatable).")
    parser.add_argument("--log-level", default="WARNING", choices=("DEBUG", "INFO", "WARNING", "ERROR"))
    args = parser.parse_args(argv)

    configure_logging(level=args.log_level)

    try:
        config = load_config(args.clusters)
        provider = build_provider(config.credentials)
    except (ConfigError, CredentialError) as exc:
        sys.stderr.write(f"Error: {exc}\n")
        return EXIT_CONFIG_ERROR

    if args.only_clusters:
        selected = set(args.only_clusters)
        for cluster in config.clusters:
            cluster.enabled = cluster.name in selected

    rows = collect(config, provider)

    if args.format == "markdown":
        print_markdown(rows)
    elif args.format == "json":
        print(json.dumps(rows, indent=2, default=str))
    else:
        for row in rows:
            if row.get("error"):
                print(f"{row['cluster']:10s} {'—':24s} ERROR {row['error_kind']}: {row['error']}")
            else:
                print(
                    f"{row['cluster']:10s} {row['remote']:24s} connected={str(row.get('connected')).lower():5s} "
                    f"nodes={row.get('nodes_connected')}/{row.get('max_connections')} "
                    f"mode={row.get('mode')} timeout={row.get('initial_connect_timeout')} "
                    f"skip_unavailable={row.get('skip_unavailable')}"
                )

    if args.emit_baseline:
        document = build_baseline(config, rows)
        with open(args.emit_baseline, "w", encoding="utf-8") as handle:
            json.dump(document, handle, indent=2)
            handle.write("\n")
        sys.stderr.write(
            f"\nWrote {args.emit_baseline}.\n"
            f"REVIEW IT before use: observed values are not agreed baselines (CCS-2).\n"
        )

    return EXIT_FAILED if any(r.get("error") for r in rows) else EXIT_OK


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
